# Generated by Django 4.1.3 on 2022-12-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='income',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='service',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, max_length=10),
        ),
    ]
