# Generated by Django 4.1.3 on 2022-11-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='balance',
        ),
        migrations.AlterField(
            model_name='service',
            name='expense',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='income',
            field=models.IntegerField(default=0),
        ),
    ]
