# Generated by Django 4.1.3 on 2022-12-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_expense_created_date_alter_income_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='time',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='time',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='time',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
