# Generated by Django 4.1.3 on 2022-12-05 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
